"""Erros de domínio da Assessment Policy.

Sem dependência de FastAPI: adapters HTTP futuros traduzirão esses erros.
"""

from __future__ import annotations

from typing import Any, Optional


class AssessmentPolicyError(Exception):
    """Erro determinístico do domínio de políticas avaliativas."""

    def __init__(self, code: str, message: str, details: Optional[Any] = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details


POLICY_NOT_FOUND = "ASSESSMENT_POLICY_NOT_FOUND"
POLICY_IMMUTABLE = "ASSESSMENT_POLICY_IMMUTABLE"
POLICY_INVALID_STATE = "ASSESSMENT_POLICY_INVALID_STATE"
POLICY_TENANT_MISMATCH = "ASSESSMENT_POLICY_TENANT_MISMATCH"
POLICY_VERSION_EXISTS = "ASSESSMENT_POLICY_VERSION_EXISTS"
POLICY_IDENTITY_IMMUTABLE = "ASSESSMENT_POLICY_IDENTITY_IMMUTABLE"
POLICY_VALIDATION_FAILED = "ASSESSMENT_POLICY_VALIDATION_FAILED"
POLICY_CONFLICT_CHECK_REQUIRED = "ASSESSMENT_POLICY_CONFLICT_CHECK_REQUIRED"
POLICY_CONFLICT = "ASSESSMENT_POLICY_CONFLICT"
POLICY_CONCURRENT_MODIFICATION = "ASSESSMENT_POLICY_CONCURRENT_MODIFICATION"

# Sprint 002 — Resolver
POLICY_REQUIRED = "ASSESSMENT_POLICY_REQUIRED"
POLICY_AMBIGUOUS = "ASSESSMENT_POLICY_AMBIGUOUS"
POLICY_INTEGRITY_ERROR = "ASSESSMENT_POLICY_INTEGRITY_ERROR"
POLICY_CONTEXT_MISMATCH = "ASSESSMENT_POLICY_CONTEXT_MISMATCH"
STUDENT_SERIES_REQUIRED = "ASSESSMENT_STUDENT_SERIES_REQUIRED"
STUDENT_SERIES_AMBIGUOUS = "ASSESSMENT_STUDENT_SERIES_AMBIGUOUS"

# Sprint 003 — Calculator / Recovery
CALCULATION_MODE_UNSUPPORTED = "ASSESSMENT_CALCULATION_MODE_UNSUPPORTED"
CALCULATION_UNKNOWN_PERIOD = "ASSESSMENT_CALCULATION_UNKNOWN_PERIOD"
CALCULATION_VALUE_INVALID = "ASSESSMENT_CALCULATION_VALUE_INVALID"
CALCULATION_VALUE_OUT_OF_SCALE = "ASSESSMENT_CALCULATION_VALUE_OUT_OF_SCALE"
CALCULATION_UNKNOWN_CONCEPT = "ASSESSMENT_CALCULATION_UNKNOWN_CONCEPT"
CALCULATION_POLICY_INVALID = "ASSESSMENT_CALCULATION_POLICY_INVALID"
RECOVERY_NOT_ENABLED = "ASSESSMENT_RECOVERY_NOT_ENABLED"
RECOVERY_UNKNOWN_INPUT = "ASSESSMENT_RECOVERY_UNKNOWN_INPUT"
RECOVERY_RULE_INCOMPLETE = "ASSESSMENT_RECOVERY_RULE_INCOMPLETE"
RECOVERY_NO_ELIGIBLE_PERIOD = "ASSESSMENT_RECOVERY_NO_ELIGIBLE_PERIOD"
RECOVERY_TIE_UNRESOLVED = "ASSESSMENT_RECOVERY_TIE_UNRESOLVED"

# Sprint 004 — Academic Outcome
OUTCOME_POLICY_INVALID = "ASSESSMENT_OUTCOME_POLICY_INVALID"
OUTCOME_VALUE_INVALID = "ASSESSMENT_OUTCOME_VALUE_INVALID"
OUTCOME_ATTENDANCE_INVALID = "ASSESSMENT_OUTCOME_ATTENDANCE_INVALID"
OUTCOME_DUPLICATE_COMPONENT = "ASSESSMENT_OUTCOME_DUPLICATE_COMPONENT"
OUTCOME_DEPENDENCY_AMBIGUOUS = "ASSESSMENT_OUTCOME_DEPENDENCY_AMBIGUOUS"

# Sprint 005 — Shadow / Dry-run
SHADOW_MAPPING_INVALID = "ASSESSMENT_SHADOW_MAPPING_INVALID"
SHADOW_LEGACY_VALUE_INVALID = "ASSESSMENT_SHADOW_LEGACY_VALUE_INVALID"
SHADOW_TOLERANCE_INVALID = "ASSESSMENT_SHADOW_TOLERANCE_INVALID"
