export const componentesData = {
  "BERÇÁRIO I": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "BERÇÁRIO II": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "MATERNAL I": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "MATERNAL II": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "PRÉ I": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "PRÉ II": [
    { nome: "O eu, o outro e o nós", cargaHoraria: 120 },
    { nome: "Corpo, gestos e movimentos", cargaHoraria: 120 },
    { nome: "Traços, sons, cores e formas", cargaHoraria: 160 },
    { nome: "Escuta, fala, pensamento e imaginação", cargaHoraria: 160 },
    {
      nome: "Espaços, tempos, quantidades, relações e transformações",
      cargaHoraria: 160,
    },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Tecnologia", cargaHoraria: 80 },
  ],
  "1º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "2º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "3º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "4º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "5º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
  ],
  "6º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 240 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 240 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 120 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Estudos Amazônicos", cargaHoraria: 80 },
    { nome: "Literatura e Redação", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "7º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 240 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 240 },
    { nome: "Ciências", cargaHoraria: 120 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Estudos Amazônicos", cargaHoraria: 80 },
    { nome: "Literatura e Redação", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "8º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 240 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 240 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 120 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
    { nome: "Estudos Amazônicos", cargaHoraria: 80 },
    { nome: "Literatura e Redação", cargaHoraria: 80 },
    { nome: "Recreação, Esporte e Lazer", cargaHoraria: 80 },
    { nome: "Arte e Cultura", cargaHoraria: 160 },
    { nome: "Tecnologia e Informática", cargaHoraria: 40 },
    {
      nome: "Acompanhamento Pedagógico de Língua Portuguesa",
      cargaHoraria: 160,
    },
    { nome: "Acompanhamento Pedagógico de Matemática", cargaHoraria: 160 },
  ],
  "9º ANO": [
    { nome: "Língua Portuguesa", cargaHoraria: 240 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 240 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 120 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
  ],
  "1ª ETAPA": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
  ],
  "2ª ETAPA": [
    { nome: "Língua Portuguesa", cargaHoraria: 160 },
    { nome: "Arte", cargaHoraria: 40 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 160 },
    { nome: "Ciências", cargaHoraria: 80 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
  ],
  "3ª ETAPA": [
    { nome: "Língua Portuguesa", cargaHoraria: 280 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 280 },
    { nome: "Ciências", cargaHoraria: 120 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
  ],
  "4ª ETAPA": [
    { nome: "Língua Portuguesa", cargaHoraria: 280 },
    { nome: "Arte", cargaHoraria: 80 },
    { nome: "Educação Física", cargaHoraria: 80 },
    { nome: "Língua Inglesa", cargaHoraria: 80 },
    { nome: "Matemática", cargaHoraria: 280 },
    { nome: "Ciências", cargaHoraria: 120 },
    { nome: "História", cargaHoraria: 80 },
    { nome: "Geografia", cargaHoraria: 80 },
    { nome: "Ensino Religioso", cargaHoraria: 40 },
    { nome: "Educação Ambiental e Clima", cargaHoraria: 80 },
  ],
  "NÃO SERIADA": [{ nome: "Atividades Complementares" }],
};
